// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haaspugoeefuabwubbdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYXNwdWdvZWVmdWFid3ViYmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTA1MDgsImV4cCI6MjA2Mzc4NjUwOH0.BlMFs3J_FPR2K2r6uJgxom2UHpBrPnb9744YDDlvUxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);